-- Purchase Orders from ApparelMagic.
-- Run ONCE in the Supabase SQL editor. Idempotent (IF NOT EXISTS / safe to re-run).
--
-- Header keyed on apparel_magic_id (= AM purchase_order_id); items nest under it.
-- All access is via the service-role key (sync routes + /api/data), so RLS is
-- enabled with no policies = service-role-only, matching the rest of the app.

CREATE TABLE IF NOT EXISTS purchase_orders (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  apparel_magic_id        text UNIQUE NOT NULL,
  vendor_id               text,
  vendor_name             text,
  vendor_po               text,
  warehouse_id            text,
  issue_from_warehouse_id text,
  location_id             text,
  division_id             text,
  project_id              text,
  project_number          text,
  process_id              text,
  process_name            text,
  process_description     text,
  step_number             text,
  receiving_status        text,
  wms_status              text,
  order_date              date,
  date_start              date,
  date_due                date,
  date_ex_factory         date,
  name                    text,
  address_1               text,
  address_2               text,
  city                    text,
  state                   text,
  postal_code             text,
  country                 text,
  phone                   text,
  shipping_name           text,
  shipping_address_1      text,
  shipping_address_2      text,
  shipping_city           text,
  shipping_state          text,
  shipping_postal_code    text,
  shipping_country        text,
  shipping_phone          text,
  shipping_address_override text,
  ship_via                text,
  shipping_terms_id       text,
  shipping_info           text,
  tracking_number         text,
  terms_id                text,
  notes                   text,
  private_notes           text,
  qty                     numeric DEFAULT 0,
  qty_open                numeric DEFAULT 0,
  qty_received            numeric DEFAULT 0,
  qty_cxl                 numeric DEFAULT 0,
  qty_in_transit          numeric DEFAULT 0,
  amount                  numeric DEFAULT 0,
  amount_open             numeric DEFAULT 0,
  amount_cxl              numeric DEFAULT 0,
  amount_subtotal         numeric DEFAULT 0,
  amount_taxable          numeric DEFAULT 0,
  amount_tax              numeric DEFAULT 0,
  amount_tax_2            numeric DEFAULT 0,
  amount_tax_total        numeric DEFAULT 0,
  amount_freight          numeric DEFAULT 0,
  amount_duty             numeric DEFAULT 0,
  amount_other            numeric DEFAULT 0,
  amount_landed_cost_est  numeric DEFAULT 0,
  override_tax_amount     numeric DEFAULT 0,
  tax_rate                numeric DEFAULT 0,
  tax_rate_2              numeric DEFAULT 0,
  tax_first_tax_amount    text,
  freight_taxable         text,
  currency_id             text,
  currency_name           text,
  currency_rate           numeric DEFAULT 1,
  foreign_amount          numeric DEFAULT 0,
  foreign_amount_open     numeric DEFAULT 0,
  foreign_amount_subtotal numeric DEFAULT 0,
  is_locked               boolean DEFAULT false,
  is_actualized           boolean DEFAULT false,
  is_printed              boolean DEFAULT false,
  is_emailed              boolean DEFAULT false,
  print_url               text,
  am_creation_time        text,
  am_creation_user_name   text,
  am_last_modified_time   text,
  am_last_modified_command text,
  am_last_modified_user_id text,
  last_synced_at          timestamptz,
  created_at              timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  am_item_id              text,
  purchase_order_id       uuid REFERENCES purchase_orders(id) ON DELETE CASCADE,
  apparel_magic_po_id     text NOT NULL,
  row_id                  text,
  warehouse_id            text,
  product_id              text,
  sku_id                  text,
  style_number            text,
  description             text,
  attr_2                  text,
  attr_3                  text,
  size                    text,
  upc                     text,
  sku_alt                 text,
  location                text,
  qty                     numeric DEFAULT 0,
  qty_open                numeric DEFAULT 0,
  qty_received            numeric DEFAULT 0,
  qty_cxl                 numeric DEFAULT 0,
  qty_in_transit          numeric DEFAULT 0,
  unit_cost               numeric DEFAULT 0,
  amount                  numeric DEFAULT 0,
  unit_cost_landed_est    numeric DEFAULT 0,
  amount_landed_est       numeric DEFAULT 0,
  foreign_amount          numeric DEFAULT 0,
  foreign_amount_landed_est numeric DEFAULT 0,
  is_taxable              boolean DEFAULT false,
  order_item_id           text,
  prepack_id              text,
  date_start              date,
  date_due                date,
  date_ex_factory         date,
  weight                  numeric DEFAULT 0,
  notes                   text,
  last_synced_at          timestamptz
);

CREATE INDEX IF NOT EXISTS idx_po_items_apparel_magic_po_id ON purchase_order_items (apparel_magic_po_id);
CREATE INDEX IF NOT EXISTS idx_po_items_purchase_order_id   ON purchase_order_items (purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_po_vendor_id                 ON purchase_orders (vendor_id);
CREATE INDEX IF NOT EXISTS idx_po_receiving_status          ON purchase_orders (receiving_status);

ALTER TABLE purchase_orders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;
-- No policies: service-role-only (sync routes + /api/data both use the service key,
-- which bypasses RLS). Add a SELECT policy later only if anon-key reads are needed.
